version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - back
      - front
  back:
    build:
      context: ./back
      target: dev
    restart: always
    volumes:
      - ./back:/app
  front:
    build:
      context: ./front
    restart: always
    environment:
      NODE_ENV: production
